export interface AIListingAnalysis {
  // Financial & Market Overview Module
  financials: {
    price_per_sqm: number;
    location_average_price_per_sqm: number;
    price_difference_percentage: number; // e.g. +6.6 or -12.0
    market_status: 'Precenjeno' | 'Realna cena' | 'Povoljno';
    seller_type: 'Direktno od Vlasnika' | 'Agencija';
  };

  // AI Deal Score Module
  deal_score: {
    score: number; // e.g. 8.5
    verdict: string; // Dynamic 1-sentence summary specific to this exact property
  };

  // Dynamic AI Risk & Highlight Detector Module
  insights: {
    risks: string[]; // Dynamic red flags (e.g., "Nije uknjiženo", "4. sprat bez lifta", "TA grejanje")
    highlights: string[]; // Dynamic pros (e.g., "Mogućnost deljenja u 2 jedinice", "Uknjižen 1/1", "Parking u dvorištu")
  };

  // DYNAMIC CONTEXTUAL QUICK PROMPTS (Listing-Specific FAQs)
  // These MUST be dynamically generated by AI based on the unique details of the specific listing
  dynamic_quick_prompts: {
    label: string; // e.g., "Procena cene renoviranja" or "Izdavanje po danu"
    prompt_query: string; // The exact question sent to AI when clicked
  }[];
}

export interface ScannedListingItem {
  id: string;
  portal_name: string; // hostname from the active page, not a hardcoded portal map
  listing_url: string;
  title: string | null;
  description: string | null;
  location: string | null;
  total_price: number | null;
  currency: 'EUR' | 'USD' | 'GBP' | 'RSD' | null;
  area_sqm: number | null;
  raw_price?: string | null;
  raw_area?: string | null;
  is_valid_listing: boolean;
  has_partial_data: boolean;
  completeness_score: 0 | 20 | 40 | 60 | 80 | 100;
  is_unlocked: boolean;
  analysis?: AIListingAnalysis;
}

export type ListingDetectionField =
  | 'price'
  | 'title'
  | 'description'
  | 'location'
  | 'surface_area';

export interface ListingDetectionResult {
  schema_version: 1;
  is_valid_listing: boolean;
  has_partial_data: boolean;
  completeness_score: 0 | 20 | 40 | 60 | 80 | 100;
  missing_fields: ListingDetectionField[];
  detection: {
    method: 'json_ld' | 'dom_heuristic' | 'hybrid' | 'none';
    confidence_score: number;
    json_ld_types: string[];
    signals: {
      has_property_schema: boolean;
      has_offer: boolean;
      has_price: boolean;
      has_title: boolean;
      has_description: boolean;
      has_location: boolean;
      has_surface_area: boolean;
      has_specs_container: boolean;
      is_collection_like: boolean;
      repeated_listing_count: number;
    };
  };
  listing: null | {
    portal_name: string;
    listing_url: string;
    title: string | null;
    description: string | null;
    location: string | null;
    price: {
      value: number | null;
      currency: 'EUR' | 'USD' | 'GBP' | 'RSD' | null;
      raw: string | null;
    };
    surface_area: {
      value: number | null;
      unit: 'sqm' | 'sqft' | null;
      sqm: number | null;
      raw: string | null;
    };
  };
}

export const AI_LISTING_ANALYSIS_JSON_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'AIListingAnalysis',
  description:
    'Listing-specific real estate analysis for one scanned Balkan property. Generate all insights and quick prompts from the unique listing facts and local market context.',
  type: 'object',
  additionalProperties: false,
  required: ['financials', 'deal_score', 'insights', 'dynamic_quick_prompts'],
  properties: {
    financials: {
      type: 'object',
      additionalProperties: false,
      description:
        'Financial and market comparison values calculated for this exact listing and its location.',
      required: [
        'price_per_sqm',
        'location_average_price_per_sqm',
        'price_difference_percentage',
        'market_status',
        'seller_type',
      ],
      properties: {
        price_per_sqm: {
          type: 'number',
          minimum: 0,
          description: 'Listing asking price divided by listed area in square meters.',
        },
        location_average_price_per_sqm: {
          type: 'number',
          minimum: 0,
          description:
            'Estimated average price per square meter for comparable properties in the same city, municipality, and micro-location when available.',
        },
        price_difference_percentage: {
          type: 'number',
          description:
            'Percentage difference between this listing price per sqm and the local average. Positive means above market; negative means below market.',
        },
        market_status: {
          type: 'string',
          enum: ['Precenjeno', 'Realna cena', 'Povoljno'],
          description: 'Market price classification based on the local price comparison.',
        },
        seller_type: {
          type: 'string',
          enum: ['Direktno od Vlasnika', 'Agencija'],
          description:
            'Whether the listing appears to be offered directly by the owner or through an agency.',
        },
      },
    },
    deal_score: {
      type: 'object',
      additionalProperties: false,
      description:
        'A concise AI deal rating for this listing, balancing price, location, condition, risks, and upside.',
      required: ['score', 'verdict'],
      properties: {
        score: {
          type: 'number',
          minimum: 0,
          maximum: 10,
          description: 'Deal attractiveness score from 0 to 10, where 10 is strongest.',
        },
        verdict: {
          type: 'string',
          minLength: 1,
          description:
            'One sentence specific to this property explaining why the score was assigned.',
        },
      },
    },
    insights: {
      type: 'object',
      additionalProperties: false,
      description:
        'Dynamic risk and highlight extraction from this listing text, pricing, floor, legal status, amenities, and location context.',
      required: ['risks', 'highlights'],
      properties: {
        risks: {
          type: 'array',
          minItems: 0,
          description:
            'Listing-specific red flags. Include only risks supported by the listing details or strong contextual inference.',
          items: {
            type: 'string',
            minLength: 1,
          },
        },
        highlights: {
          type: 'array',
          minItems: 0,
          description:
            'Listing-specific advantages. Include only benefits supported by the listing details or strong contextual inference.',
          items: {
            type: 'string',
            minLength: 1,
          },
        },
      },
    },
    dynamic_quick_prompts: {
      type: 'array',
      minItems: 1,
      description:
        'Context-aware FAQ prompts generated uniquely for this listing. Avoid generic prompts; each item should address a decision the buyer or investor would naturally ask about this property.',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['label', 'prompt_query'],
        properties: {
          label: {
            type: 'string',
            minLength: 1,
            description: 'Short Serbian UI label for the listing-specific question.',
          },
          prompt_query: {
            type: 'string',
            minLength: 1,
            description:
              'Exact Serbian question to send to the AI when clicked, grounded in this listing details.',
          },
        },
      },
    },
  },
} as const;
